name: Get latest Svelte 5 release version

on:
  schedule:
    - cron: '0 10 * * *'

  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  get-release:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch release version
        id: get_version
        run: |
          curl -s https://api.github.com/repos/sveltejs/svelte/releases | jq -r '.[] | select(.tag_name | contains("svelte@5.0.0-next")) | .tag_name' | sed 's/svelte@//' | sort -V | tail -n 1 > release-versions/sveltejs/svelte-latest.txt
          RELEASE_TAG=$(cat release-versions/sveltejs/svelte-latest.txt)
          echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
          echo "latest release: $RELEASE_TAG"
      - name: Check for modified files
        id: git_status
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "modified=true" >> $GITHUB_OUTPUT
          else
            echo "modified=false" >> $GITHUB_OUTPUT
          fi
      - name: Commit Changes
        if: steps.git_status.outputs.modified == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            release-versions/sveltejs/svelte-latest.txt
          message: 'New release version ${{ steps.get_version.outputs.release_tag }}'
